apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: employee-dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      - name: postgres

        image: postgres:16

        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_DB
          value: employeedb

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: employee-secret
              key: DB_USERNAME

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: employee-secret
              key: DB_PASSWORD
